### ISSUE TITLE
Annotation of 0 seqs with 0 annots finished

### ISSUE THREAD

**Issue by agolicz** [peterjc/galaxy_blast#72] opened 2015-10-27 23:22 UTC
Sorry, please ignore. I have managed to solve the problem, but seem unable to delete the issue.
Best wishes,
Agnieszka

**Comment by bgruening** [comment] 2015-10-28 07:27
You should be able to close the issue. @peterjc can for sure :)

**Comment by peterjc** [comment] 2015-10-28 09:45
I saw the related thread on the Blast2GO Google Group, resolved as being caused by an annoying typo at the command line:

*The problem has been solved. It was a simple case of ``-`` missing before ``annot``. I have typed ``annot`` instead of ``-annot``.*

Most command line tools will give an error if an unexpected command line option is used.

Closing this issue - glad you could solve it :)

**Closed by peterjc** 2015-10-28 09:45 UTC
