### ISSUE TITLE
 Problems with NCBI BLAST+ 2.5.0 and dependency errors installing from the tool shed

### ISSUE THREAD

**Issue by charesredhat** [peterjc/galaxy_blast#99] opened 2017-12-01 18:13 UTC
Hi I installed NCBI BLAST+ 2.5.0 from the tool shed and I am using it as a dependency for the wrapper with Seqsero. But every time I install it I get the following error 

[samopen] SAM header is present: 6 sequences.
makeblastdb: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
blastn: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/nfs/sw/apps/galaxy-dev/ga

And this is after I uninstalled the tool and then enabled conda channels 

conda_ensure_channels = iuc,bioconda,conda-forge,defaults,r

in the ini cleared the conda cache and restarted the galaxy and then reisntalled the tool and made sure the the blast package was installed by conda.
This is all happened on a galley instance running on CentOS server. 

But on my local galaxy instance running on a Mac the it runs fine installing it from the tool shed I don’t any errors saying it can load makeblastdb or blastn.

Could it be a problem with conda and CentOS?

**Comment by peterjc** [comment] 2017-12-04 14:33
I doubt it is relevant, but what is Seqsero and is that on the Galaxy tool shed?

Are you installing the Galaxy dependencies (like BLAST) via BioConda (and not the legacy Galaxy XML-based tool shed package system)?

What version of conda do you have?

Can you check and tell us which version of the BioConda BLAST package was installed? My guess is this is a problem in the BLAST recipe (BioConda changed from using the NCBI provided binaries to compiling it themselves).

Are you able to try installing BLAST via Conda (same version as determined above), and running ``makeblastdb`` and ``blastn`` OUTSIDE of Galaxy? That would confirm where the problem is.

Thanks!

**Comment by peterjc** [comment] 2017-12-04 14:44
Cross reference https://github.com/galaxyproject/tools-iuc/issues/1613

**Comment by peterjc** [comment] 2018-10-19 14:36
Closing due to lack of information to follow this up.

**Closed by peterjc** 2018-10-19 14:36 UTC
